assoc .json=sourcecode
assoc .js=sourcecode
assoc .cpp=sourcecode
assoc .cxx=sourcecode
assoc .cs=sourcecode
assoc .cc=sourcecode
assoc .c=sourcecode
assoc .h=sourcecode
assoc .hxx=sourcecode
assoc .hpp=sourcecode
assoc .pl=sourcecode
assoc .py=""
assoc .rs=sourcecode
assoc .log=sourcecode
assoc .txt=sourcecode
assoc .xml=sourcecode
assoc .=sourcecode
ftype sourcecode="C:\Program Files (x86)\Vim\vim80\gvim.exe" --remote-silent "%%1"
