---
- hosts: localhost
  sudo: true
  tasks:

    - name: 'arch misc setup'
      pacman: name=git state=latest
      pacman: name=vim state=latest
      when: ansible_os_family == 'Archlinux'

    - name: 'arch C dev setup'
      pacman: name=make state=latest
      pacman: name=gcc state=latest
      pacman: name=clang state=latest
      when: ansible_os_family == 'Archlinux'

    - name: 'arch python dev setup'
      pacman: name=python state=latest
      pacman: name=python-dev state=latest
      pacman: name=python2 state=latest
      pacman: name=python2-dev state=latest
      pacman: name=pypy state=latest
      when: ansible_os_family == 'Archlinux'

    - name: 'symlink localtime'
      file: path=/etc/localtime state=absent
      file: path=/etc/localtime
            src=/usr/share/zoneinfo/America/Los_Angeles
            state=link
            force=yes
      when: ansible_os_family == 'Archlinux'

    - name: 'copy configs to /etc'
      copy: src={{ item }} dest=/etc
      with_fileglob:
        - ../arch/etc/*
      when: ansible_os_family == 'Archlinux'

    # Hack because ansible doesn't do recursive copy -- what the hell??
    - name: 'copy xorg configs to /etc'
      copy: src={{ item }} dest=/etc/X11/xorg.conf.d
      with_fileglob:
        - ../arch/etc/X11/xorg.conf.d/*
      when: ansible_os_family == 'Archlinux'

    - name: 'copy xorg configs to /etc'
      copy: src={{ item }} dest=/etc/modprobe.d
      with_fileglob:
        - ../arch/etc/modprobe.d/*
      when: ansible_os_family == 'Archlinux'



    - name: 'Set up gui'
      pacman: name=xorg state=latest
      pacman: name=xorg-xinit state=latest
      pacman: name=i3 state=latest
      pacman: name=dmenu state=latest
      pacman: name=nvidia state=latest
      pacman: name=xclip state=latest
      pacman: name=xterm state=latest
      pacman: name=firefox state=latest
      when: ansible_os_family == 'Archlinux'


