---
- hosts: all
  tasks:
    - include_vars: vars.yml

    - name: 'install gg'
      git: repo=https://github.com/iankronquist/gg
           dest={{ ansible_env.HOME }}/gg/gg
           update=yes

    - name: 'get dotfiles'
      git: repo=https://github.com/iankronquist/dotfiles
           dest={{ ansible_env.HOME }}/dotfiles
           update=yes

    - name: 'make dirs'
      file: path={{ ansible_env.HOME }}/gg state=directory
      file: path={{ ansible_env.HOME }}/.ssh state=directory

    - name: 'install config files'
      file: path={{ ansible_env.HOME }}/item.value.dest state=absent
      file: path={{ ansible_env.HOME }}/{{ item.value.dest }}
            src={{ ansible_env.HOME }}/dotfiles/{{ item.value.src }}
            state=link
            force=yes
      with_dict: files

    - name: 'install config dirs'
      file: path={{ ansible_env.HOME }}/{{ item.value.dest }} state=absent
      file: path={{ ansible_env.HOME }}/{{ item.value.dest }}
            src={{ ansible_env.HOME }}/dotfiles/{{ item.value.src }}
            state=link
            force=yes
      with_dict: directories


- hosts: ash
  tasks:
    - name: 'install ash specific config files'
      file: path={{ ansible_env.HOME }}/item.value.dest state=absent
      file: path={{ ansible_env.HOME }}/{{ item.value.dest }}
            src={{ ansible_env.HOME }}/dotfiles/{{ item.value.src }}
            state=link
            force=yes
      with_dict: ash
